name: Deploy to Google Cloud VM
on:
    push:
        branches:
            - main
            - feature/devops
            - cloud-deploy
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4      
              
            - name: Login to docker hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push docker image
              uses: docker/build-push-action@v2
              with:
                context: ./src
                push: true
                tags: sandside/myflix:website