name: Deploy to Google Cloud VM
on:
    push:
        branches:
            - main
            - cloud-deploy
    pull_request:
        branches:
          - main
          - cloud-deploy
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4      
              
            - name: Login to docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push docker image
              uses: docker/build-push-action@v5
              with:
                context: ./src/myflix-website
                push: true
                tags: sandside/myflix:website

            - name: Pull and run image in VM
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.VM_IP }}
                username: ${{ secrets.VM_USERNAME }}
                key: ${{ secrets.VM_SSH_KEY }}
                script: |
                    docker stop myflix-website
                    docker rm myflix-website
                    docker pull sandside/myflix:website
                    docker run -d -p 80:8080 --restart=always --name myflix-website sandside/myflix:website

            